[package]
name = "rsquant"
version = "0.1.0"
authors = ["ccyanxyz <ccyanxyz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
error-chain = { version = "0.12", default-features = false }
ring = "0.16"
reqwest = { version = "0.10", features = ["blocking", "json"] }
tungstenite = "0.10"
url = "2.1"
