[package]
name = "rsex"
version = "0.1.0"
authors = ["ccyanxyz <ccyanxyz@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
env_logger = "0.7.1"
log = "0.4.8"
ws = { version = "0.9.1", features = ["ssl"]}
flate2 = "1.0"
lazy_static = "1.4.0"
hex = "0.4.2"
base64 = "0.12.1"
chrono = "0.4"
percent-encoding = "1.0.1"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
ring = "0.13.0-alpha"
data-encoding = "2.1.2"
reqwest = { version = "0.10", features = ["blocking", "json"] }
url = "2.1"
